version: '3'

services:
  python3:
    image: ghcr.io/turbou/contrast-documentation-rss/python3:1.0.2
    platform: linux/amd64
    build: .
    container_name: 'rssgen.python3'
    tty: true
    volumes:
      - ./work:/work
      - ./files:/files
      - ./feeds:/feeds

