# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rssgen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/turbou/contrastsecurity/rssgen_python3:1.0.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Check Python Version
        run: python -V

